require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - "Gemfile"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
